services:
  mcp_tools_config.config_management:
    class: Drupal\mcp_tools_config\Service\ConfigManagementService
    arguments:
      - '@config.factory'
      - '@config.storage'
      - '@config.storage.sync'
      - '@state'
      - '@file_system'
      - '@mcp_tools.access_manager'
      - '@mcp_tools.audit_logger'

  mcp_tools_config.config_change_subscriber:
    class: Drupal\mcp_tools_config\EventSubscriber\McpConfigChangeSubscriber
    arguments:
      - '@mcp_tools_config.config_management'
      - '@mcp_tools.tool_call_context'
    tags:
      - { name: event_subscriber }
